version: '3'
services:
  mongo:
    build: 
      context: './mongo'
      args:
        - 'MONGO_INITDB_USERNAME=${DB_USER}'
        - 'MONGO_INITDB_PASSWORD=${DB_PASSWORD}'
        - 'MONGO_INITDB_DATABASE=${DB_NAME}'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${MONGODB_PORT}:27017'
    command: [--auth]
    volumes:
      - '${DATA_PATH_HOST}/mongo:/data/db'
      - '${DATA_PATH_HOST}/mongo_config:/data/configdb'
  mongo-client:
    build: 
      context: './mongo-client'
    ports:
      - '${MONGODB_CLIENT_PORT}:8000'
volumes: {}
