name: Mongodb 

on:
  schedule:
  - cron:  '00 23 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MongoDB-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Mongodb
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DATA_PATH_HOST: /tmp/mongo
    - name: MongoDB Version check
      run: docker exec mongodb_mongo_1 mongo | grep MongoDB
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/mongo
    - name: Create ENV
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: |
          echo "$ENV_TEST" > .env.test
        shell: bash
      - name: Notify on SUCCESS
        if: ${{ SUCCESS() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>" 
          mention_users: "U056E1KTCTG,"
          mention_users_when: "SUCCESS"
          mention_groups: "C06H0SB11JL, !github_action_success"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
      - name: Notify on FAIL
        if: ${{ failure() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          mention_users: "U056E1KTCTG"
          mention_users_when: "failure,warnings"
          mention_groups: "C06G95T1YH3,!github_action_failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
  MongoDB-ARM64:
    runs-on: ubuntu-22.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    name: MongoDB-ARM64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
      - name: Build the Docker image Mongodb
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          DATA_PATH_HOST: /tmp/mongo
      - name: MongoDB Version check
        run: docker exec mongodb_mongo_1 mongo | grep MongoDB
      - name: Destroy container and file
        run:  |
          docker-compose down
          echo "y" | docker system prune -a
          sudo rm -rf /tmp/mongo
      - name: Create ENV
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: |
          echo "$ENV_TEST" > .env.test
        shell: bash
      - name: Notify on SUCCESS
        if: ${{ SUCCESS() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>" 
          mention_users: "U056E1KTCTG,"
          mention_users_when: "SUCCESS"
          mention_groups: "C06H0SB11JL, !github_action_success"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
      - name: Notify on FAIL
        if: ${{ failure() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          mention_users: "U056E1KTCTG"
          mention_users_when: "failure,warnings"
          mention_groups: "C06G95T1YH3,!github_action_failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
