name: Mongodb 

on:
  schedule:
  - cron:  '00 23 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # MongoDB-AMD64:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, self-hosted]
  #   runs-on: ${{ matrix.os }}
  #   env:
  #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image Mongodb
  #     run: docker-compose -f "docker-compose.yml" up -d --build
  #     env:
  #       DATA_PATH_HOST: /tmp/mongo
  #   - name: MongoDB Version check
  #     run: docker exec mongodb_mongo_1 mongo | grep MongoDB
  MongoDB:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Mongodb
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DATA_PATH_HOST: /tmp/mongo
    - name: MongoDB Version check
      # run:  docker-compose ps
      run: docker exec mongodb_mongo_1 mongo | grep MongoDB
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/mongo
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with: 
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        channel: '#github_action_status'
      if: always()
  